agent_config:
  ai_model:
    model_params:
      api_key: sk-f3ee5353f375f45271fd55792e91564a
      base_url: https://apis.iflow.cn/v1/chat/completions
      debug: false
      llm: qwen3-coder-plus
      temperature: 0.7
      tokenizer: null
    model_type: qwen3-coder-plus
env_config:
  n_guard: 1
  n_hunter: 0
  n_player: 9
  n_role: 5
  n_seer: 1
  n_villager: 3
  n_werewolf: 3
  n_witch: 1
human_player:
  enabled: true
  player_id: 5
