# 人类 vs Qwen3-Next-80B-A3B-Instruct 对战配置
env_config:
    n_player: 9
    n_role: 5
    n_werewolf: 3
    n_seer: 1
    n_guard: 1
    n_witch: 1
    n_villager: 3
    n_hunter: 0

# agent assignment
agent_config:
    werewolf:
        model_type: human
        model_params:
            tokenizer: null
            llm: null
            temperature: 0.7
            debug: false
    villager:
        model_type: qwen3-coder-plus
        model_params:
            tokenizer: null
            llm: qwen3-coder-plus
            temperature: 0.7
            base_url: https://apis.iflow.cn/v1/chat/completions
            api_key: sk-f3ee5353f375f45271fd55792e91564a
            debug: false
